### ISSUE TITLE
What problem does tetra solve?

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/tetra#20]
I've read through the README.md file, but I'm left with a few questions that I was hoping would generate some conversation, ultimately culminating in an update to the README.md file (by me or someone else).
- What problem does tetra actually solve?  Why is this a problem?
- Why would I care about tetra?  When should I use tetra vs. other tools of a similar nature?  ARE there tools of a similar nature?
- How does tetra distinguish passing and failing tests?
- Can I use tetra with other, non-Python testing tools?

I'm wondering because one of our projects mentioned tetra in a Github issue as a desirable tool to integrate with, but when I came here to learn more about tetra, I have as many questions now as I did before reading the README.  Hopefully, this will allow me to get a better understanding of tetra, when (not) to use it, etc.

Thanks!!

**Comment by pglass** [comment]
This is still a proof of concept side project, with lots to improve.

The core idea is to:

- store test results in a relatively consistent format
- make those results available via a rest api (so that tools and dashboards can be written to make analyzing results faster and easier)

> What problem does tetra actually solve? Why is this a problem?

If you are running tests on a regular basis and enough of those tests are flaky (sometimes fail, sometimes not) that sifting through the failures manually would consume too much time.

There are other goals, like presenting a cross-project view of test results, but analyzing flaky tests quickly is the main use case so far.

> Why would I care about tetra? When should I use tetra vs. other tools of a similar nature? ARE there tools of a similar nature?

There are things like elasticsearch which will index and search through unstructured data (and which has an api and dashboards) which have been used for this and which you may prefer to use. 

There is the openstack health dashboard: http://status.openstack.org/openstack-health. This this is strung together with a bunch of pieces and designed specifically for openstack test infrastructure. It is built on top of elasticsearch and a database (iirc).

> How does tetra distinguish passing and failing tests?

Right now, it just looks at a string: https://github.com/rackerlabs/tetra/blob/master/tetra/data/models/result_metadata.py#L56-L63. Obviously, this may not be generic enough for every kind of test result you could put into tetra. It's not finalized and it worked for the use case we had.

> Can I use tetra with other, non-Python testing tools?

Right now, if you have test results in "xunit-style xml" then yes (it's using https://pypi.python.org/pypi/xunitparser to parse the xml. I don't know how standardized this format is). The main thing is it works with xml generated by the junit jenkins plugin, so if you have that you just send it to tetra. 

A goal is to handle any kind of test results (within reason), but that work hasn't been put in because this is a side project for now.
